version: "3"

services:
    api:
        restart: always
        container_name: recommendation_system_api
        build: ./
        volumes:
            - ./:/app
        ports:
            - "5000:5000"
